# theme: technophile-jekyll-theme
defaults:
  - scope:
      path: ''
      type: 'categories'
    values:
      layout: 'category'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
    values:
      layout: 'default'
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag