# theme: technophile-jekyll-theme
defaults:
  - scope:
      path: ''
      type: categories
    values:
      layout: category
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      permalink: /blog/:categories/:slug
      categories: ''
      slug: ''
      tags: ''
      author: 'AquisTech'
  - scope:
      path: pages
      type: pages
    values:
      layout: page
  - scope:
      path: ''
    values:
      layout: default
collections:
  categories:
    output: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-admin
company: true
email: aquistech@gmail.com
phone: +917977519229
formatted_phone: +91 79775 19229